2023/03/07 17:50:15 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: mysite.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8888"
2023/03/07 17:53:00 [error] 31#31: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: mysite.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8888"
2023/03/07 18:04:42 [error] 31#31: *38 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#1 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OF
2023/03/07 18:04:42 [error] 31#31: *38 FastCGI sent in stderr: "ata',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '51938',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1678212282.843973,
    'REQUEST_TIME' => 1678212282,
    'argv' => [],
    'argc' => 0,
]" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:06:05 [error] 31#31: *40 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 31. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(Error))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#4 {main}
Previous exception:
Error: Class "app\widgets\Alert" not found in /application/views/layouts/main.php:51
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(347): require()
#1 /application/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/application/vi...', Array)
#2 /application/vendor/yiisoft/yii2/base/Controller.php(422): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#3 /application/vendor/yiisoft/yii2/base/Controller.php(408): yii\base\Controller->renderContent('<div class="sit...')
#4 /application/controllers/SiteController.php(32): yii\base\Controller->render('index')
#5 [internal function]: app\controllers\SiteController->actionIndex()
#6 /application/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#9 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#10 /application/vendor/yiisoft/yii2/ba" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:06:05 [error] 31#31: *40 FastCGI sent in stderr: "se/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /application/web/index.php(13): yii\base\Application->run()
#12 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USE
2023/03/07 18:07:41 [error] 31#31: *44 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#1 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OF
2023/03/07 18:07:41 [error] 31#31: *44 FastCGI sent in stderr: "ata',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '53200',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1678212461.432721,
    'REQUEST_TIME' => 1678212461,
    'argv' => [],
    'argc' => 0,
]" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:08:50 [error] 31#31: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/dashboard/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\DashboardController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\DashboardController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('dashboard/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the re" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:08:50 [error] 31#31: *49 FastCGI sent in stderr: "quest "". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_
2023/03/07 18:08:59 [error] 31#31: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/dashboard/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\DashboardController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\DashboardController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('dashboard/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the re" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:08:59 [error] 31#31: *49 FastCGI sent in stderr: "quest "". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_
2023/03/07 18:09:00 [error] 31#31: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/dashboard/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\DashboardController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\DashboardController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('dashboard/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the re" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:09:00 [error] 31#31: *49 FastCGI sent in stderr: "quest "". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_
2023/03/07 18:12:11 [error] 31#31: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "dashboard/error". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('dashboard/error')
#1 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF
2023/03/07 18:12:11 [error] 31#31: *64 FastCGI sent in stderr: "   'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '49050',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1678212731.192665,
    'REQUEST_TIME' => 1678212731,
    'argv' => [],
    'argc' => 0,
]" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi
2023/03/07 18:12:12 [error] 31#31: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "dashboard/error". in /application/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('dashboard/error')
#1 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF
2023/03/07 18:12:12 [error] 31#31: *64 FastCGI sent in stderr: "   'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '49050',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1678212731.997712,
    'REQUEST_TIME' => 1678212731,
    'argv' => [],
    'argc' => 0,
]" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi
2023/03/07 18:12:20 [error] 31#31: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:12:20 [error] 31#31: *64 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:12:37 [error] 31#31: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:12:37 [error] 31#31: *64 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:12:38 [error] 31#31: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:12:38 [error] 31#31: *64 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:14:28 [error] 31#31: *70 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:14:28 [error] 31#31: *70 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:14:35 [error] 31#31: *70 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:14:39 [error] 31#31: *70 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:14:39 [error] 31#31: *70 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:14 [error] 31#31: *79 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:14 [error] 31#31: *79 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:15 [error] 31#31: *79 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:15 [error] 31#31: *79 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:16 [error] 31#31: *79 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:16 [error] 31#31: *79 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:35 [error] 31#31: *83 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:35 [error] 31#31: *83 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:36 [error] 31#31: *83 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:36 [error] 31#31: *83 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:15:36 [error] 31#31: *83 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:15:36 [error] 31#31: *83 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:16:49 [error] 31#31: *87 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:16:49 [error] 31#31: *87 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:17:04 [error] 31#31: *87 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request: site/index in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
#1 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/index')
#2 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#4 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERS
2023/03/07 18:17:04 [error] 31#31: *87 FastCGI sent in stderr: "p.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=ef4443d11a265d26216e9f417b24ddf50696cc0f7a0f84f2633fd6338238a0e1a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22l2R_SGofLqKT-mV27fqN7rLhlYhA2o1e%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '49576',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' 
2023/03/07 18:17:20 [error] 31#31: *87 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:17:20 [error] 31#31: *87 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:17:24 [error] 31#31: *87 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\ViewNotFoundException: The view file does not exist: /application/views/site/error.php in /application/vendor/yiisoft/yii2/base/View.php:233
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/application/vi...', Array, Object(app\controllers\SiteController))
#1 /application/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('error', Array, Object(app\controllers\SiteController))
#2 /application/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#3 /application/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\web\ErrorAction->renderHtmlResponse()
#4 [internal function]: yii\web\ErrorAction->run()
#5 /application/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#6 /application/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#7 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('error', Array)
#8 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('site/error')
#9 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#10 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#11 {main}
Previous" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:17:24 [error] 31#31: *87 FastCGI sent in stderr: " exception:
yii\base\InvalidRouteException: Unable to resolve the request: site/ in /application/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#1 /application/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#2 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /application/web/index.php(13): yii\base\Application->run()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /application/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /application/web/index.php(13): yii\base\Application->run()
#2 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
   
2023/03/07 18:19:41 [error] 31#31: *92 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/
2023/03/07 18:19:41 [error] 31#31: *92 FastCGI sent in stderr: "
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '44204',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1678213181.547865,
    'REQUEST_TIME' => 1678213181,
    'argv' => [],
    'argc' => 0,
]" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:25:13 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD286428" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:25:13 [error] 31#31: *1 FastCGI sent in stderr: "24F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=dbe5f19545ebadbcd0e1e586674365f9376398778bd049f837ca06d50723889ea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%225E9taFsAf9_NkGa5uz0ajfGmA0eqEohN%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0',
    'HTTP_HOST' => 'localhost:8888',
    'SCRIPT_FILENAME' => '/application/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '',
    'SERVER_PORT' => '80',
    'SERVER_ADDR' => '172.19.0.2',
    'REMOTE_PORT' => '46134',
    'REMOTE_ADDR' => '172.19.0.1',
    'SERVER_SOFTWARE' => 'nginx/1.21.3',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/application/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => 
2023/03/07 18:25:20 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->sendHeaders()
#1 /application/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /application/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /application/controllers/SiteController.php on line 28. in /application/vendor/yiisoft/yii2/web/Response.php:368
Stack trace:
#0 /application/vendor/yiisoft/yii2/web/Response.php(341): yii\web\Response->" while reading upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost:8888"
2023/03/07 18:25:20 [error] 31#31: *1 FastCGI sent in stderr: "sendHeaders()
#1 /application/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#2 /application/web/index.php(13): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'HOSTNAME' => '0ee4f1bda2ec',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    'HOME' => '/var/www',
    'PHP_IDE_CONFIG' => 'serverName=docker',
    'PHP_LDFLAGS' => '-Wl,-O1 -pie',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_VERSION' => '8.0.5',
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz.asc',
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.5.tar.xz',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c',
    'PWD' => '/application',
    'PHP_SHA256' => '5dd358b35ecd5890a4f09fb68035a72fe6b45d3ead6999ea95981a107fd1f2ab',
    'USER' => 'www-data',
    'HTTP_SEC_FETCH_SITE' => 'cross-site',
    'HTTP_SEC_FETCH_MODE' => 'navigate',
    'HTTP_SEC_FETCH_DEST' => 'document',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_COOKIE' => 'PHPSESSID=fng4h2k4kdncus8rcgb7t1l96b; _csrf=dbe5f19545ebadbcd0e1e586674365f9376398778bd049f837ca06d50723889ea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%225E9taFsAf9_NkGa5uz0ajfGmA0eqEohN%22%3B%7D',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_DNT' => '1',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
